# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    # create a group of dependencies to be updated together in one pull request
    groups:
      # specify a name for the group, which will be used in pull request titles
      # and branch names
      dependencies:
        # define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"  # matches all dependencies in the package ecosystem

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"  # group all updates into a single larger pull request
