name: Black Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  black-check:
    name: Check Code Style Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check Code Style
        run: |
          black --check .
          sed -i -e '$a\' .github/workflows/black-check.yml
